SERVERSIDE_USUARIOS_TABLE_COLUMNS = [
    {
        "data_name": "Activo",
        "column_name": "Activo",
        "default": "",
        "order": 1,
        "searchable": True,
    },
    {
        "data_name": "Actualizado",
        "column_name": "Actualizado",
        "default": "",
        "order": 8,
        "searchable": False,
    },
    {
        "data_name": "Apellido",
        "column_name": "Apellido",
        "default": 0,
        "order": 3,
        "searchable": False,
    },
    {
        "data_name": "Email",
        "column_name": "Email",
        "default": 0,
        "order": 6,
        "searchable": False,
    },
    {
        "data_name": "ID",
        "column_name": "ID",
        "default": 0,
        "order": 0,
        "searchable": False,
    },
    {
        "data_name": "Nombre",
        "column_name": "Nombre",
        "default": 0,
        "order": 2,
        "searchable": False,
    },
    {
        "data_name": "Nombre de usuario",
        "column_name": "Nombre de usuario",
        "default": 0,
        "order": 5,
        "searchable": True,
    },
    {
        "data_name": "Registrado",
        "column_name": "Registrado",
        "default": 0,
        "order": 7,
        "searchable": False,
    },
    {
        "data_name": "Rol",
        "column_name": "Rol",
        "default": 0,
        "order": 4,
        "searchable": False,
    },
]

SERVERSIDE_DOCENTES_TABLE_COLUMNS = [
    {
        "data_name": "activo",
        "column_name": "Activo",
        "default": "",
        "order": 1,
        "searchable": False,
    },
    {
        "data_name": "tipo de documento",
        "column_name": "Tipo de Documento",
        "default": "",
        "order": 8,
        "searchable": False,
    },
    {
        "data_name": "apellido",
        "column_name": "Apellido",
        "default": 0,
        "order": 3,
        "searchable": True,
    },
    {
        "data_name": "domicilio",
        "column_name": "Domicilio",
        "default": 0,
        "order": 6,
        "searchable": False,
    },
    {
        "data_name": "id",
        "column_name": "ID",
        "default": 0,
        "order": 0,
        "searchable": False,
    },
    {
        "data_name": "nombre",
        "column_name": "Nombre",
        "default": 0,
        "order": 2,
        "searchable": True,
    },
    {
        "data_name": "localidad",
        "column_name": "Localidad",
        "default": 0,
        "order": 5,
        "searchable": False,
    },
    {
        "data_name": "genero",
        "column_name": "Genero",
        "default": 0,
        "order": 7,
        "searchable": False,
    },
    {
        "data_name": "fecha de nacimiento",
        "column_name": "Fecha de Nacimiento",
        "default": 0,
        "order": 4,
        "searchable": False,
    },
    {
        "data_name": "numero",
        "column_name": "Numero de Documento",
        "default": "",
        "order": 9,
        "searchable": False,
    },
    {
        "data_name": "tel",
        "column_name": "Numero telefónico",
        "default": "",
        "order": 10,
        "searchable": False,
    },
    {
        "data_name": "Creado",
        "column_name": "Creado",
        "default": 0,
        "order": 11,
        "searchable": False,
    },
    {
        "data_name": "Actualizado",
        "column_name": "Actualizado",
        "default": 0,
        "order": 12,
        "searchable": False,
    },
]
