-- MySQL Script generated by MySQL Workbench
-- Fri 25 Oct 2019 01:31:31 AM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema grupo2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `grupo2` ;

-- -----------------------------------------------------
-- Schema grupo2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `grupo2` DEFAULT CHARACTER SET utf8 ;
USE `grupo2` ;

-- -----------------------------------------------------
-- Table `grupo2`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` CHAR(60) NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `grupo2`.`nucleos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`nucleos` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`nucleos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `coordenadas` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo2`.`orquestas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`orquestas` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`orquestas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo2`.`ensayos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`ensayos` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`ensayos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_orquesta` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `ubicacion_ciudad` VARCHAR(45) NOT NULL,
  `ubicacion_calle` VARCHAR(45) NOT NULL,
  `ubicacion_numero` VARCHAR(45) NULL,
  `ubicacion_coordenadas` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_orquesta_idx` (`id_orquesta` ASC),
  CONSTRAINT `id_orquesta`
    FOREIGN KEY (`id_orquesta`)
    REFERENCES `grupo2`.`orquestas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo2`.`opciones_instrumentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`opciones_instrumentos` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`opciones_instrumentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo2`.`instrumentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`instrumentos` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`instrumentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_opciones_instrumentos` INT NOT NULL,
  `numero_item` TINYINT NOT NULL,
  `fecha_adquirido` DATE NOT NULL,
  `observaciones` TINYTEXT NULL,
  `ubicacion_actual` TINYTEXT NOT NULL,
  `ubicacion_actual_coordenadas` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_opciones_instrumentos_idx` (`id_opciones_instrumentos` ASC),
  CONSTRAINT `id_opciones_instrumentos`
    FOREIGN KEY (`id_opciones_instrumentos`)
    REFERENCES `grupo2`.`opciones_instrumentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo2`.`alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`alumnos` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`alumnos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres_apellidos` VARCHAR(45) NOT NULL,
  `DNI` VARCHAR(8) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `padre_madre_tutor` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `domicilio_ciudad` VARCHAR(45) NOT NULL,
  `domicilio_calle` VARCHAR(45) NOT NULL,
  `domicilio_numero` VARCHAR(6) NOT NULL,
  `domicilio_barrio` VARCHAR(45) NOT NULL,
  `domicilio_coordenadas` TINYTEXT NULL,
  `año` TINYINT NOT NULL,
  `turno` VARCHAR(45) NOT NULL,
  `escuela` VARCHAR(45) NOT NULL,
  `id_profesor` INT NOT NULL,
  `fecha_comienzo` DATE NOT NULL,
  `id_opciones_instrumentos` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_opciones_instrumentos_idx` (`id_opciones_instrumentos` ASC),
  CONSTRAINT `alumnos_id_opciones_instrumentos`
    FOREIGN KEY (`id_opciones_instrumentos`)
    REFERENCES `grupo2`.`opciones_instrumentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo2`.`prestamos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`prestamos` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`prestamos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_instrumento` INT NOT NULL,
  `id_alumno` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_instrumento_idx` (`id_instrumento` ASC),
  INDEX `id_alumno_idx` (`id_alumno` ASC),
  CONSTRAINT `id_instrumento`
    FOREIGN KEY (`id_instrumento`)
    REFERENCES `grupo2`.`instrumentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_alumno`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `grupo2`.`alumnos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo2`.`reparacion_instrumento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`reparacion_instrumento` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`reparacion_instrumento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_instrumento` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `descripcion` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_instrumento_idx` (`id_instrumento` ASC),
  CONSTRAINT `reparacion_instrumento_id_instrumento`
    FOREIGN KEY (`id_instrumento`)
    REFERENCES `grupo2`.`instrumentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo2`.`accesorios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`accesorios` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`accesorios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `observaciones` TINYTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo2`.`actividades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`actividades` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`actividades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_nucleo` INT NOT NULL,
  `id_opciones_instrumentos` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `hora_inicio` DATE NOT NULL,
  `hora_fin` VARCHAR(45) NOT NULL,
  `dia_semana` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_nucleo_idx` (`id_nucleo` ASC),
  INDEX `id_opciones_instrumentos_idx` (`id_opciones_instrumentos` ASC),
  CONSTRAINT `id_nucleo`
    FOREIGN KEY (`id_nucleo`)
    REFERENCES `grupo2`.`nucleos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `actividades_id_opciones_instrumentos`
    FOREIGN KEY (`id_opciones_instrumentos`)
    REFERENCES `grupo2`.`opciones_instrumentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo2`.`alumno_actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`alumno_actividad` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`alumno_actividad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_alumno` INT NOT NULL,
  `id_actividad` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `nivel` TINYTEXT NULL,
  INDEX `id_alumno_idx` (`id_alumno` ASC),
  INDEX `id_actividad_idx` (`id_actividad` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `alumno_actividad_id_alumno`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `grupo2`.`alumnos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `alumno_actividad_id_actividad`
    FOREIGN KEY (`id_actividad`)
    REFERENCES `grupo2`.`actividades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo2`.`alumno_orquesta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`alumno_orquesta` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`alumno_orquesta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_alumno` INT NOT NULL,
  `id_orquesta` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_alumno_idx` (`id_alumno` ASC),
  INDEX `id_orquesta_idx` (`id_orquesta` ASC),
  CONSTRAINT `alumno_orquesta_id_alumno`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `grupo2`.`alumnos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `alumno_orquesta_id_orquesta`
    FOREIGN KEY (`id_orquesta`)
    REFERENCES `grupo2`.`orquestas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo2`.`asistencias_inasistencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`asistencias_inasistencias` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`asistencias_inasistencias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `id_alumno_actividad` INT NOT NULL,
  `observaciones_logros` TINYTEXT NULL,
  `inasistencia_justificacion` TINYTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_alumno_actividad_idx` (`id_alumno_actividad` ASC),
  CONSTRAINT `id_alumno_actividad`
    FOREIGN KEY (`id_alumno_actividad`)
    REFERENCES `grupo2`.`alumno_actividad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo2`.`profesores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`profesores` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`profesores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_apellido` TINYTEXT NOT NULL,
  `DNI` VARCHAR(8) NOT NULL,
  `fecha_inicio` TINYTEXT NOT NULL,
  `cargo` TINYTEXT NOT NULL,
  `domicilio_ciudad` TINYTEXT NOT NULL,
  `domicilio_calle` TINYTEXT NOT NULL,
  `domicilio_numero` VARCHAR(6) NOT NULL,
  `domicilio_coordenadas` TINYTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo2`.`profesor_actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`profesor_actividad` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`profesor_actividad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_profesor` INT NOT NULL,
  `id_actividad` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  INDEX `id_actividad_idx` (`id_actividad` ASC),
  PRIMARY KEY (`id`),
  INDEX `id_profesor_idx` (`id_profesor` ASC),
  CONSTRAINT `id_profesor`
    FOREIGN KEY (`id_profesor`)
    REFERENCES `grupo2`.`profesores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_actividad`
    FOREIGN KEY (`id_actividad`)
    REFERENCES `grupo2`.`actividades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo2`.`preceptores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`preceptores` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`preceptores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_apellido` TINYTEXT NOT NULL,
  `DNI` VARCHAR(8) NOT NULL,
  `fecha_inicio` TINYTEXT NOT NULL,
  `cargo` TINYTEXT NOT NULL,
  `domicilio_ciudad` TINYTEXT NOT NULL,
  `domicilio_calle` TINYTEXT NOT NULL,
  `domicilio_numero` VARCHAR(6) NOT NULL,
  `domicilio_coordenadas` TINYTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo2`.`preceptor_actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`preceptor_actividad` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`preceptor_actividad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_preceptor` INT NOT NULL,
  `id_actividad` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  INDEX `id_actividad_idx` (`id_actividad` ASC),
  PRIMARY KEY (`id`),
  INDEX `id_preceptor_idx` (`id_preceptor` ASC),
  CONSTRAINT `id_preceptor`
    FOREIGN KEY (`id_preceptor`)
    REFERENCES `grupo2`.`preceptores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `preceptor_actividad_id_actividad`
    FOREIGN KEY (`id_actividad`)
    REFERENCES `grupo2`.`actividades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo2`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`rol` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`rol` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo2`.`usuario_tiene_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`usuario_tiene_rol` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`usuario_tiene_rol` (
  `usuario_id` INT(11) NOT NULL,
  `rol_id` INT(11) NOT NULL,
  INDEX `usuario_id_idx` (`usuario_id` ASC),
  INDEX `rol_id_idx` (`rol_id` ASC),
  PRIMARY KEY (`rol_id`, `usuario_id`),
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `grupo2`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_rol_id`
    FOREIGN KEY (`rol_id`)
    REFERENCES `grupo2`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo2`.`permiso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`permiso` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`permiso` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo2`.`rol_tiene_permiso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`rol_tiene_permiso` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`rol_tiene_permiso` (
  `rol_id` INT(11) NOT NULL,
  `permiso_id` INT(11) NOT NULL,
  INDEX `rol_id_idx` (`rol_id` ASC),
  INDEX `permiso_id_idx` (`permiso_id` ASC),
  PRIMARY KEY (`permiso_id`, `rol_id`),
  CONSTRAINT `rol_id`
    FOREIGN KEY (`rol_id`)
    REFERENCES `grupo2`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `permiso_id`
    FOREIGN KEY (`permiso_id`)
    REFERENCES `grupo2`.`permiso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo2`.`config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo2`.`config` ;

CREATE TABLE IF NOT EXISTS `grupo2`.`config` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `descripcion` TEXT(255) NOT NULL,
  `email_contacto` VARCHAR(255) NOT NULL,
  `modo_mantenimiento` TINYINT(1) NOT NULL,
  `items_por_pagina` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
