SERVERSIDE_USUARIOS_TABLE_COLUMNS = [
    {
        "data_name": "Activo",
        "column_name": "Activo",
        "default": "",
        "order": 1,
        "searchable": True,
    },
    {
        "data_name": "Actualizado",
        "column_name": "Actualizado",
        "default": "",
        "order": 8,
        "searchable": False,
    },
    {
        "data_name": "Apellido",
        "column_name": "Apellido",
        "default": 0,
        "order": 3,
        "searchable": False,
    },
    {
        "data_name": "Email",
        "column_name": "Email",
        "default": 0,
        "order": 6,
        "searchable": False,
    },
    {
        "data_name": "ID",
        "column_name": "ID",
        "default": 0,
        "order": 0,
        "searchable": False,
    },
    {
        "data_name": "Nombre",
        "column_name": "Nombre",
        "default": 0,
        "order": 2,
        "searchable": False,
    },
    {
        "data_name": "Nombre de usuario",
        "column_name": "Nombre de usuario",
        "default": 0,
        "order": 5,
        "searchable": True,
    },
    {
        "data_name": "Registrado",
        "column_name": "Registrado",
        "default": 0,
        "order": 7,
        "searchable": False,
    },
    {
        "data_name": "Rol",
        "column_name": "Rol",
        "default": 0,
        "order": 4,
        "searchable": False,
    },
]
